mytestsite/mytestsite/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from rango import views
from django.conf import settings
from registration.backends.simple.views import RegistrationView
from django.core.urlresolvers import reverse


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$',
        MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

mytestsite/rango/urls.py
from django.conf.urls import url
from rango import views


app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^add_category/$', views.AddCategory.as_view(), name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/?$',
        views.category, name='category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.AddPage.as_view(), name='add_page'),
    url(r'^add/$', views.auto_add_page, name='auto_add_page'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_profile/$', views.RegisterProfile.as_view(),
        name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$',
        views.Profile.as_view(), name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^goto/$', views.track_url, name='goto'),
]

mytestsite/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone
#import itertools


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # if orig:
        #     orig += '-'
        # for x in itertools.count(1):
        #     if not Category.objects.filter(slug=self.slug).exists():
        #         break
        #     self.slug = ("{0}{1}").format(orig, x)
        # #self.full_clean()
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    first_visit = models.DateTimeField(default=timezone.now, blank=True)
    last_visit = models.DateTimeField(default=timezone.now, blank=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

mytestsite/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text='Please enter the category name')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=128,
                         help_text='Please enter the url of the page')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = self.cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data

    class Meta:
        model = Page
        exclude = ('category',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

mytestsite/rango/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.utils import timezone
from datetime import datetime
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rango.google_search import run_search


def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    pages_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'top_pages': pages_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context_dict)
    return response


def about(request):
    request.session.set_test_cookie()
    visitor_cookie_handler(request)
    context_dict = {'bmess': 'Artem', 'visits': request.session['visits']}
    return render(request, 'rango/about.html', context_dict)


def category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name

        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages

        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
        context_dict['category_name'] = None

    context_dict['query'] = context_dict['category_name']
    results = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            results = run_search(query)
            context_dict['query'] = query
            context_dict['results'] = results

    return render(request, 'rango/category.html', context_dict)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]

    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET.get('suggestion', '')
    cat_list = get_category_list(8, starts_with)

    return render(request, 'rango/cats.html', {'cats': cat_list})


@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET.get('category_id', None)
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()

        return HttpResponse(likes)


def track_url(request):
    page_id = None
    url = reverse('rango:index')
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']

            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.last_visit = timezone.now()
                page.save()
                url = page.url
            except Exception:
                pass
    return redirect(url)


def search(request):
    results = []
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            results = run_search(query)
    return render(request, 'rango/search.html', {
        'results': results,
        'query': query
    })


@method_decorator(login_required, name='dispatch')
class AddCategory(View):
    form_class = CategoryForm
    template_name = 'rango/add_category.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            return render(request, self.template_name, {'form': form})


@login_required
def auto_add_page(request):
    cat_id = None
    url = None
    title = None
    context_dict = {}
    if request.method == 'GET':
        cat_id = request.GET.get('category_id', None)
        url = request.GET.get('url', None)
        title = request.GET.get('title', None)
        if cat_id and url and title:
            category = Category.objects.get(id=int(cat_id))
            p = Page.objects.get_or_create(
                category=category, title=title, url=url)
            pages = Page.objects.filter(category=category).order_by('-views')
            context_dict['pages'] = pages

    return render(request, 'rango/page_list.html', context_dict)


class AddPage(View):
    form_class = PageForm
    template_name = 'rango/add_page.html'
    category_name_slug = None

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.category_name_slug = kwargs.get('category_name_slug', None)
        try:
            self.category = Category.objects.get(slug=self.category_name_slug)
        except Category.DoesNotExist:
            self.category = None
        return super(AddPage, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context_dict = {'form': form,
                        'category': self.category,
                        'category_name_slug': self.category_name_slug
                        }
        return render(request, self.template_name, context_dict)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid() and self.category:
            page = form.save(commit=False)
            page.category = self.category
            page.views = 0
            page.save()
            return HttpResponseRedirect(reverse(
                'rango:category',
                kwargs={'category_name_slug': self.category_name_slug}))
        else:
            return render(request, self.template_name,
                          {'form': form, 'category': self.category})


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                profile.save()
                registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered
                   }
                  )


class Profile(View):
    form_class = UserProfileForm
    template_name = 'rango/profile.html'
    username = None

    def dispatch(self, request, *args, **kwargs):
        try:
            self.username = kwargs.get('username', None)
            self.user = User.objects.get(username=self.username)
        except User.DoesNotExist:
            return redirect('rango:index')

        self.userprofile = UserProfile.objects.get_or_create(user=self.user)[0]

        return super(Profile, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(
            {'website': self.userprofile.website,
             'picture': self.userprofile.picture}
        )
        context = {
            'form': form,
            'selecteduser': self.user,
            'userprofile': self.userprofile
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(
            request.POST,
            request.FILES,
            instance=self.userprofile
        )
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', self.user.username)
        else:
            context = {
                'form': form,
                'selecteduser': self.user,
                'userprofile': self.userprofile
            }
            return render(request, self.template_name, context)


def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    return render(request,
                  'rango/list_profiles.html',
                  {'userprofile_list': userprofile_list}
                  )


@method_decorator(login_required, name='dispatch')
class RegisterProfile(View):
    form_class = UserProfileForm
    template_name = 'rango/profile_registration.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        try:
            profile = request.user.userprofile
        except UserProfile.DoesNotExist:
            profile = UserProfile(user=request.user)

        form = self.form_class(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            user_profile = form.save(commit=False)

mytestsite/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}About page{% endblock %}
{% block body_block %}
    <h1>About page</h1>
    This tutorial has been put together by <strong>{{ bmess }}</strong><br />
    <button class="btn btn-primary" id="about-btn">CLick me</button>
    <p>This text is for a JQuery Example</p>
    <div id="msg">Hello - I'm here for a JQuery Example too</div>
    <img src="{% static "images/rango.jpg" %}" alt="Rango" />
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Mew" />
    <br />Number visits: {{ visits }}
{% endblock %}

mytestsite/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load bootstrap_toolkit %}
{% block title_block %}Add category{% endblock %}
{% block body_block %}
    <h1>Add category</h1>
    <form role="form" id="category_form" method="POST" action="{% url 'rango:add_category' %}">
        <h2 class="form-signin-heading">Add category</h2>
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <br />
        <button class="btn btn-primary" type="submit" name="submit">Add category</button>
    </form>
{% endblock %}

mytestsite/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% block title_block %}Add page{% endblock %}
{% block body_block %}
    {% if category %}
        <h1>Add page into "{{ category }}"</h1>
        <form role="form" id="page_form" method="POST" action="{% url 'rango:add_page' category.slug %}">
            <h2 class="form-signin-heading">Add a page to <a href="{% url 'rango:category' category.slug %}">{{category.name }}</a></h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                {{ field.help_text }}<br />
                {{ field }}<br />
            {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit">Add page</button>
            </form>
    {% else %}
    <p>Request category doesn't exist for add page</p>
    {% endif %}
{% endblock %}

mytestsite/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/rango-ajax.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>Rango - {% block title_block %}Main page{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Rango</a>

      <div id="navbar">
        <nav class="nav navbar-dark pull-xs-left">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:about' %}">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:profile' user.username %}">My profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:restricted' %}">Restricted area</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:add_category' %}">Add category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_login' %}">Sign in</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:list_profiles' %}">User Profiles</a>
            </li>
          </ul>
        </nav>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-list">
                <li class="nav-header">Type to find category</li>
                    <li><form><input type="text" name="suggestion" class="search-query form-control" id="suggestion" value="" /></form>
                    </li>
            </ul>
            <hr>
            <div id="cats"></div>
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
          {% block body_block %}{% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

mytestsite/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}{{ category.name }}{% endblock %}
{% block body_block %}
    {% if category %}
        <h1>{{ category_name }}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
        {% if user.is_authenticated %}
            <button id="likes" data-catid="{{category.id}}" class="btn btn-priary btn-sm" type="button">Like</button>
        {% endif %}
        </div>
        {% if pages %}
        <div id="pages">
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                        {% if page.views > 1 %}
                            ({{ page.views }} views)
                        {% elif page.views == 1 %}
                            ({{ page.views }} view)
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% else %}
            <strong>Not pages in currently in category</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add page in current the category</a>
        {% endif %}
        <div>
            <form class="form-inline" id="user_form" method="POST" action="{% url 'rango:category' category.slug %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="query" class="form-control" value="{{ query }}" id="query" size="50">
                    </div>
                    <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
            </form>
            {% if results %}
                <div>
                    <h3>Results</h3>
                    <div class="list-group">
                        {% for result in results %}
                        <div class="list-group-item">
                            <h4 class="list-group-heading">
                                <a href="{{ result.link }}">{{ result.title }}</a>
                            {% if user.is_authenticated %}
                                <button data-catid="{{ category.id }}" data-title="{{ result.title }}" data-url="{{ result.link }}" class="rango-add btn btn-info btn-sm" type="button">Add</button>
                            {% endif %}
                            </h4>
                            <p class="list-group-item-text">{{ result.snippet }}</p>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
        </div>
    {% else %}
        <strong>Specified category {{ category_name }} doesn't exist!</strong>
    {% endif %}
{% endblock %}

mytestsite/templates/rango/cats.html
<ul class="list-group">
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li class="list-group-item list-group-item-success">
                    <a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a>
                </li>
            {% else %}
                <li class="list-group-item list-group-item-action">
                    <a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories for present</strong></li>
    {% endif %}
</ul>

mytestsite/templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}List of profiles{% endblock %}
{% block body_block %}
    <h1>User profiles</h1>
    <div class="panel">
    {% if userprofile_list %}
        <div class="panel-heading">
            <div class="panel-body">
                <div class="list-group">
                {% for listuser in userprofile_list %}
                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">
                        {% if listuser.picture %}
                            <img src="{{ MEDIA_URL }}{{ listuser.picture }}" width="64" height="64" alt="Avatar for {{ listuser.user.username }}" />
                        {% else %}
                            <img width="64" height="64" src="http://lorempixel.com/64/64/people/" alt="Avatar for {{ listuser.user.username }}" />
                        {% endif %}
                            <a href="{% url 'rango:profile' listuser.user.username %}">{{ listuser.user.username }}</a>
                        </h4>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <p>There are no user for the site.</p>
    {% endif %}
    </div>
{% endblock %}

mytestsite/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}Login{% endblock %}
{% block body_block %}
    <h1>Login to site</h1>
    {% if error %}
        <ul style="color:red;">
            <li>{{ error }}</li>
        </ul>
    {% endif %}
    <form id="login_form" method="POST" action="{% url 'rango:login' %}">
        {% csrf_token %}
        <p>
            Login: <input type="text" name="username" value="" size="20" /><br />
        </p>
        <p>
            Password: <input type="password" name="password" value="" size="20" /><br />
        </p>
        <p>
            <input type="submit" name="submit" value="Sign in" />
        </p>
    </form>
{% endblock %}

mytestsite/templates/rango/page_list.html
{% if pages %}
<ul>
{% for page in pages %}
    <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{page.title}}</a>
    {% if page.views > 1 %}
        ({{ page.views }} views)
    {% elif page.views == 1 %}
        ({{ page.views }} view)
    {% endif %}
    </li>
{% endfor %}
</ul>
{% else %}
    <strong>No pages currently in category.</strong>
{% endif %}

mytestsite/templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}{{ selecteduser.username }}{% endblock %}
{% block body_block %}
    <h1>{{ selecteduser.username }} Profile</h1>
    <img src="{{ MEDIA_URL }}{{ userprofile.picture }}" width="300" height="300" alt="{{selecteduser.username }}" />
    <br />
    <div>
        {% if selecteduser.username == user.username %}
            <form class="form-signin" method="POST" enctype="multipart/form-data" action=".">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="brn brn-primary" type="submit" name="submit">Update</button>
            </form>
        {% elif userprofile.website %}
            <p>
                <strong>Website:</strong>&nbsp;<a href="{{ userprofile.website }}" rel="noindex">{{ userprofile.website }}</a>
            </p>
        {% endif %}
    </div>
{% endblock %}

mytestsite/templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load bootstrap_toolkit %}
{% block title_block %}Registration - Step 2{% endblock %}
{% block body_block %}
    <h1>Registration - Step 2</h1>
    <form enctype="multipart/form-data" method="POST" action=".">
        {% csrf_token %}
        <div class="form-group">
            {{ form|as_bootstrap }}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Submit</button>
        </div>
    </form>
{% endblock %}

mytestsite/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}Register{% endblock %}

{% block body_block %}
    <h1>Register page</h1>
    {% if registered %}
        <strong>Tnank you for registration!</strong><br />
        <a href="{% url 'rango:index' %}">Return to main page</a>
    {% else %}
        <strong>Registration form</strong>
        <form id="user_id" action="{% url 'rango:register' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ user_form.as_table }}
                {{ profile_form.as_table }}
            <tr><td colspan="2" align="center"><input type="submit" name="submit" value="Register"></td></tr>
            </table>
        </form>
    {% endif %}
{% endblock %}

mytestsite/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}Restricted area{% endblock %}
{% block body_block %}
    <h1>Restricted page</h1>
    <p style="color: green;">You're in restricted page!</p>
    <strong>Good luck!</strong><br />
    <a href="{% url 'auth_password_change' %}">Change yourself password</a>
{% endblock %}

mytestsite/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}Search{% endblock %}
{% block body_block %}
<div>
    <h1>Search on web</h1>
    <br />
    <form class="form-inline" id="user_form" method="POST" action="{% url 'rango:search' %}">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="query" class="form-control" value="{{ query }}" id="query">
        </div>
        <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
    </form>
    {% if results %}
    <div>
        <h3>Results</h3>
        <div class="list-group">
            {% for result in results %}
            <div class="list-group-item">
                <h4 class="list-group-heading">
                    <a href="{{ result.link }}">{{ result.title }}</a>
                </h4>
                <p class="list-group-item-text">{{ result.snippet }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}